/**
 * Nigerian States and Local Government Areas data
 */

export interface LGA {
  id: string
  name: string
}

export interface State {
  id: string
  name: string
  lgas: LGA[]
}

export const nigerianStates: State[] = [
  {
    id: "abia",
    name: "Abia",
    lgas: [
      { id: "aba-north", name: "Aba North" },
      { id: "aba-south", name: "Aba South" },
      { id: "arochukwu", name: "Arochukwu" },
      { id: "bende", name: "Bende" },
      { id: "ikwuano", name: "Ikwuano" },
      { id: "isiala-ngwa-north", name: "Isiala Ngwa North" },
      { id: "isiala-ngwa-south", name: "Isiala Ngwa South" },
      { id: "isuikwuato", name: "Isuikwuato" },
      { id: "obi-ngwa", name: "Obi Ngwa" },
      { id: "ohafia", name: "Ohafia" },
      { id: "osisioma-ngwa", name: "Osisioma Ngwa" },
      { id: "ugwunagbo", name: "Ugwunagbo" },
      { id: "ukwa-east", name: "Ukwa East" },
      { id: "ukwa-west", name: "Ukwa West" },
      { id: "umuahia-north", name: "Umuahia North" },
      { id: "umuahia-south", name: "Umuahia South" },
      { id: "umu-nneochi", name: "Umu Nneochi" },
    ],
  },
  {
    id: "adamawa",
    name: "Adamawa",
    lgas: [
      { id: "demsa", name: "Demsa" },
      { id: "fufure", name: "Fufure" },
      { id: "ganye", name: "Ganye" },
      { id: "girei", name: "Girei" },
      { id: "gombi", name: "Gombi" },
      { id: "guyuk", name: "Guyuk" },
      { id: "hong", name: "Hong" },
      { id: "jada", name: "Jada" },
      { id: "lamurde", name: "Lamurde" },
      { id: "madagali", name: "Madagali" },
      { id: "maiha", name: "Maiha" },
      { id: "mayo-belwa", name: "Mayo Belwa" },
      { id: "michika", name: "Michika" },
      { id: "mubi-north", name: "Mubi North" },
      { id: "mubi-south", name: "Mubi South" },
      { id: "numan", name: "Numan" },
      { id: "shelleng", name: "Shelleng" },
      { id: "song", name: "Song" },
      { id: "toungo", name: "Toungo" },
      { id: "yola-north", name: "Yola North" },
      { id: "yola-south", name: "Yola South" },
    ],
  },
  {
    id: "akwa-ibom",
    name: "Akwa Ibom",
    lgas: [
      { id: "abak", name: "Abak" },
      { id: "eastern-obolo", name: "Eastern Obolo" },
      { id: "eket", name: "Eket" },
      { id: "esit-eket", name: "Esit Eket" },
      { id: "essien-udim", name: "Essien Udim" },
      { id: "etim-ekpo", name: "Etim Ekpo" },
      { id: "etinan", name: "Etinan" },
      { id: "ibeno", name: "Ibeno" },
      { id: "ibesikpo-asutan", name: "Ibesikpo Asutan" },
      { id: "ibiono-ibom", name: "Ibiono Ibom" },
      { id: "ika", name: "Ika" },
      { id: "ikono", name: "Ikono" },
      { id: "ikot-abasi", name: "Ikot Abasi" },
      { id: "ikot-ekpene", name: "Ikot Ekpene" },
      { id: "ini", name: "Ini" },
      { id: "itu", name: "Itu" },
      { id: "mbo", name: "Mbo" },
      { id: "mkpat-enin", name: "Mkpat Enin" },
      { id: "nsit-atai", name: "Nsit Atai" },
      { id: "nsit-ibom", name: "Nsit Ibom" },
      { id: "nsit-ubium", name: "Nsit Ubium" },
      { id: "obot-akara", name: "Obot Akara" },
      { id: "okobo", name: "Okobo" },
      { id: "onna", name: "Onna" },
      { id: "oron", name: "Oron" },
      { id: "oruk-anam", name: "Oruk Anam" },
      { id: "udung-uko", name: "Udung Uko" },
      { id: "ukanafun", name: "Ukanafun" },
      { id: "uruan", name: "Uruan" },
      { id: "urue-offong-oruko", name: "Urue-Offong/Oruko" },
      { id: "uyo", name: "Uyo" },
    ],
  },
  {
    id: "anambra",
    name: "Anambra",
    lgas: [
      { id: "aguata", name: "Aguata" },
      { id: "anambra-east", name: "Anambra East" },
      { id: "anambra-west", name: "Anambra West" },
      { id: "anaocha", name: "Anaocha" },
      { id: "awka-north", name: "Awka North" },
      { id: "awka-south", name: "Awka South" },
      { id: "ayamelum", name: "Ayamelum" },
      { id: "dunukofia", name: "Dunukofia" },
      { id: "ekwusigo", name: "Ekwusigo" },
      { id: "idemili-north", name: "Idemili North" },
      { id: "idemili-south", name: "Idemili South" },
      { id: "ihiala", name: "Ihiala" },
      { id: "njikoka", name: "Njikoka" },
      { id: "nnewi-north", name: "Nnewi North" },
      { id: "nnewi-south", name: "Nnewi South" },
      { id: "ogbaru", name: "Ogbaru" },
      { id: "onitsha-north", name: "Onitsha North" },
      { id: "onitsha-south", name: "Onitsha South" },
      { id: "orumba-north", name: "Orumba North" },
      { id: "orumba-south", name: "Orumba South" },
      { id: "oyi", name: "Oyi" },
    ],
  },
  // Bauchi State
  {
    id: "bauchi",
    name: "Bauchi",
    lgas: [
      { id: "alkaleri", name: "Alkaleri" },
      { id: "bauchi", name: "Bauchi" },
      { id: "bogoro", name: "Bogoro" },
      { id: "damban", name: "Damban" },
      { id: "darazo", name: "Darazo" },
      { id: "dass", name: "Dass" },
      { id: "gamawa", name: "Gamawa" },
      { id: "ganjuwa", name: "Ganjuwa" },
      { id: "giade", name: "Giade" },
      { id: "itas-gadau", name: "Itas/Gadau" },
      { id: "jamaare", name: "Jama'are" },
      { id: "katagum", name: "Katagum" },
      { id: "kirfi", name: "Kirfi" },
      { id: "misau", name: "Misau" },
      { id: "ningi", name: "Ningi" },
      { id: "shira", name: "Shira" },
      { id: "tafawa-balewa", name: "Tafawa Balewa" },
      { id: "toro", name: "Toro" },
      { id: "warji", name: "Warji" },
      { id: "zaki", name: "Zaki" },
    ],
  },
  // Bayelsa State
  {
    id: "bayelsa",
    name: "Bayelsa",
    lgas: [
      { id: "brass", name: "Brass" },
      { id: "ekeremor", name: "Ekeremor" },
      { id: "kolokuma-opokuma", name: "Kolokuma/Opokuma" },
      { id: "nembe", name: "Nembe" },
      { id: "ogbia", name: "Ogbia" },
      { id: "sagbama", name: "Sagbama" },
      { id: "southern-ijaw", name: "Southern Ijaw" },
      { id: "yenagoa", name: "Yenagoa" },
    ],
  },
  // Benue State
  {
    id: "benue",
    name: "Benue",
    lgas: [
      { id: "ado", name: "Ado" },
      { id: "agatu", name: "Agatu" },
      { id: "apa", name: "Apa" },
      { id: "buruku", name: "Buruku" },
      { id: "gboko", name: "Gboko" },
      { id: "guma", name: "Guma" },
      { id: "gwer-east", name: "Gwer East" },
      { id: "gwer-west", name: "Gwer West" },
      { id: "katsina-ala", name: "Katsina-Ala" },
      { id: "konshisha", name: "Konshisha" },
      { id: "kwande", name: "Kwande" },
      { id: "logo", name: "Logo" },
      { id: "makurdi", name: "Makurdi" },
      { id: "obi", name: "Obi" },
      { id: "ogbadibo", name: "Ogbadibo" },
      { id: "ohimini", name: "Ohimini" },
      { id: "oju", name: "Oju" },
      { id: "okpokwu", name: "Okpokwu" },
      { id: "otukpo", name: "Otukpo" },
      { id: "tarka", name: "Tarka" },
      { id: "ukum", name: "Ukum" },
      { id: "ushongo", name: "Ushongo" },
      { id: "vandeikya", name: "Vandeikya" },
    ],
  },
  // Borno State
  {
    id: "borno",
    name: "Borno",
    lgas: [
      { id: "abadam", name: "Abadam" },
      { id: "askira-uba", name: "Askira/Uba" },
      { id: "bama", name: "Bama" },
      { id: "bayo", name: "Bayo" },
      { id: "biu", name: "Biu" },
      { id: "chibok", name: "Chibok" },
      { id: "damboa", name: "Damboa" },
      { id: "dikwa", name: "Dikwa" },
      { id: "gubio", name: "Gubio" },
      { id: "guzamala", name: "Guzamala" },
      { id: "gwoza", name: "Gwoza" },
      { id: "hawul", name: "Hawul" },
      { id: "jere", name: "Jere" },
      { id: "kaga", name: "Kaga" },
      { id: "kala-balge", name: "Kala/Balge" },
      { id: "konduga", name: "Konduga" },
      { id: "kukawa", name: "Kukawa" },
      { id: "kwaya-kusar", name: "Kwaya Kusar" },
      { id: "mafa", name: "Mafa" },
      { id: "magumeri", name: "Magumeri" },
      { id: "maiduguri", name: "Maiduguri" },
      { id: "marte", name: "Marte" },
      { id: "mobbar", name: "Mobbar" },
      { id: "monguno", name: "Monguno" },
      { id: "ngala", name: "Ngala" },
      { id: "nganzai", name: "Nganzai" },
      { id: "shani", name: "Shani" },
    ],
  },
  // Cross River State
  {
    id: "cross-river",
    name: "Cross River",
    lgas: [
      { id: "abi", name: "Abi" },
      { id: "akamkpa", name: "Akamkpa" },
      { id: "akpabuyo", name: "Akpabuyo" },
      { id: "bakassi", name: "Bakassi" },
      { id: "bekwarra", name: "Bekwarra" },
      { id: "biase", name: "Biase" },
      { id: "boki", name: "Boki" },
      { id: "calabar-municipal", name: "Calabar Municipal" },
      { id: "calabar-south", name: "Calabar South" },
      { id: "etung", name: "Etung" },
      { id: "ikom", name: "Ikom" },
      { id: "obanliku", name: "Obanliku" },
      { id: "obubra", name: "Obubra" },
      { id: "obudu", name: "Obudu" },
      { id: "odukpani", name: "Odukpani" },
      { id: "ogoja", name: "Ogoja" },
      { id: "yakuur", name: "Yakuur" },
      { id: "yala", name: "Yala" },
    ],
  },
  // Delta State
  {
    id: "delta",
    name: "Delta",
    lgas: [
      { id: "aniocha-north", name: "Aniocha North" },
      { id: "aniocha-south", name: "Aniocha South" },
      { id: "bomadi", name: "Bomadi" },
      { id: "burutu", name: "Burutu" },
      { id: "ethiope-east", name: "Ethiope East" },
      { id: "ethiope-west", name: "Ethiope West" },
      { id: "ika-north-east", name: "Ika North East" },
      { id: "ika-south", name: "Ika South" },
      { id: "isoko-north", name: "Isoko North" },
      { id: "isoko-south", name: "Isoko South" },
      { id: "ndokwa-east", name: "Ndokwa East" },
      { id: "ndokwa-west", name: "Ndokwa West" },
      { id: "okpe", name: "Okpe" },
      { id: "oshimili-north", name: "Oshimili North" },
      { id: "oshimili-south", name: "Oshimili South" },
      { id: "patani", name: "Patani" },
      { id: "sapele", name: "Sapele" },
      { id: "udu", name: "Udu" },
      { id: "ughelli-north", name: "Ughelli North" },
      { id: "ughelli-south", name: "Ughelli South" },
      { id: "ukwuani", name: "Ukwuani" },
      { id: "uvwie", name: "Uvwie" },
      { id: "warri-north", name: "Warri North" },
      { id: "warri-south", name: "Warri South" },
      { id: "warri-south-west", name: "Warri South West" },
    ],
  },
  // Ebonyi State
  {
    id: "ebonyi",
    name: "Ebonyi",
    lgas: [
      { id: "abakaliki", name: "Abakaliki" },
      { id: "afikpo-north", name: "Afikpo North" },
      { id: "afikpo-south", name: "Afikpo South" },
      { id: "ebonyi", name: "Ebonyi" },
      { id: "ezza-north", name: "Ezza North" },
      { id: "ezza-south", name: "Ezza South" },
      { id: "ikwo", name: "Ikwo" },
      { id: "ishielu", name: "Ishielu" },
      { id: "ivo", name: "Ivo" },
      { id: "izzi", name: "Izzi" },
      { id: "ohaozara", name: "Ohaozara" },
      { id: "ohaukwu", name: "Ohaukwu" },
      { id: "onicha", name: "Onicha" },
    ],
  },
  // Edo State
  {
    id: "edo",
    name: "Edo",
    lgas: [
      { id: "akoko-edo", name: "Akoko-Edo" },
      { id: "egor", name: "Egor" },
      { id: "esan-central", name: "Esan Central" },
      { id: "esan-north-east", name: "Esan North-East" },
      { id: "esan-south-east", name: "Esan South-East" },
      { id: "esan-west", name: "Esan West" },
      { id: "etsako-central", name: "Etsako Central" },
      { id: "etsako-east", name: "Etsako East" },
      { id: "etsako-west", name: "Etsako West" },
      { id: "igueben", name: "Igueben" },
      { id: "ikpoba-okha", name: "Ikpoba-Okha" },
      { id: "oredo", name: "Oredo" },
      { id: "orhionmwon", name: "Orhionmwon" },
      { id: "ovia-north-east", name: "Ovia North-East" },
      { id: "ovia-south-west", name: "Ovia South-West" },
      { id: "owan-east", name: "Owan East" },
      { id: "owan-west", name: "Owan West" },
      { id: "uhunmwonde", name: "Uhunmwonde" },
    ],
  },
  // Ekiti State
  {
    id: "ekiti",
    name: "Ekiti",
    lgas: [
      { id: "ado-ekiti", name: "Ado-Ekiti" },
      { id: "efon", name: "Efon" },
      { id: "ekiti-east", name: "Ekiti East" },
      { id: "ekiti-south-west", name: "Ekiti South-West" },
      { id: "ekiti-west", name: "Ekiti West" },
      { id: "emure", name: "Emure" },
      { id: "gbonyin", name: "Gbonyin" },
      { id: "ido-osi", name: "Ido-Osi" },
      { id: "ijero", name: "Ijero" },
      { id: "ikere", name: "Ikere" },
      { id: "ikole", name: "Ikole" },
      { id: "ilejemeje", name: "Ilejemeje" },
      { id: "irepodun-ifelodun", name: "Irepodun/Ifelodun" },
      { id: "ise-orun", name: "Ise/Orun" },
      { id: "moba", name: "Moba" },
      { id: "oye", name: "Oye" },
    ],
  },
  // Enugu State
  {
    id: "enugu",
    name: "Enugu",
    lgas: [
      { id: "aninri", name: "Aninri" },
      { id: "awgu", name: "Awgu" },
      { id: "enugu-east", name: "Enugu East" },
      { id: "enugu-north", name: "Enugu North" },
      { id: "enugu-south", name: "Enugu South" },
      { id: "ezeagu", name: "Ezeagu" },
      { id: "igbo-etiti", name: "Igbo-Etiti" },
      { id: "igbo-eze-north", name: "Igbo-Eze North" },
      { id: "igbo-eze-south", name: "Igbo-Eze South" },
      { id: "isi-uzo", name: "Isi-Uzo" },
      { id: "nkanu-east", name: "Nkanu East" },
      { id: "nkanu-west", name: "Nkanu West" },
      { id: "nsukka", name: "Nsukka" },
      { id: "oji-river", name: "Oji River" },
      { id: "udenu", name: "Udenu" },
      { id: "udi", name: "Udi" },
      { id: "uzo-uwani", name: "Uzo-Uwani" },
    ],
  },
  // Gombe State
  {
    id: "gombe",
    name: "Gombe",
    lgas: [
      { id: "akko", name: "Akko" },
      { id: "balanga", name: "Balanga" },
      { id: "billiri", name: "Billiri" },
      { id: "dukku", name: "Dukku" },
      { id: "funakaye", name: "Funakaye" },
      { id: "gombe", name: "Gombe" },
      { id: "kaltungo", name: "Kaltungo" },
      { id: "kwami", name: "Kwami" },
      { id: "nafada", name: "Nafada" },
      { id: "shongom", name: "Shongom" },
      { id: "yamaltu-deba", name: "Yamaltu/Deba" },
    ],
  },
  // Imo State
  {
    id: "imo",
    name: "Imo",
    lgas: [
      { id: "aboh-mbaise", name: "Aboh Mbaise" },
      { id: "ahiazu-mbaise", name: "Ahiazu Mbaise" },
      { id: "ehime-mbano", name: "Ehime Mbano" },
      { id: "ezinihitte", name: "Ezinihitte" },
      { id: "ideato-north", name: "Ideato North" },
      { id: "ideato-south", name: "Ideato South" },
      { id: "ihitte-uboma", name: "Ihitte/Uboma" },
      { id: "ikeduru", name: "Ikeduru" },
      { id: "isiala-mbano", name: "Isiala Mbano" },
      { id: "isu", name: "Isu" },
      { id: "mbaitoli", name: "Mbaitoli" },
      { id: "ngor-okpala", name: "Ngor Okpala" },
      { id: "njaba", name: "Njaba" },
      { id: "nkwerre", name: "Nkwerre" },
      { id: "nwangele", name: "Nwangele" },
      { id: "obowo", name: "Obowo" },
      { id: "oguta", name: "Oguta" },
      { id: "ohaji-egbema", name: "Ohaji/Egbema" },
      { id: "okigwe", name: "Okigwe" },
      { id: "onuimo", name: "Onuimo" },
      { id: "orlu", name: "Orlu" },
      { id: "orsu", name: "Orsu" },
      { id: "oru-east", name: "Oru East" },
      { id: "oru-west", name: "Oru West" },
      { id: "owerri-municipal", name: "Owerri Municipal" },
      { id: "owerri-north", name: "Owerri North" },
      { id: "owerri-west", name: "Owerri West" },
    ],
  },
  {
    id: "lagos",
    name: "Lagos",
    lgas: [
      { id: "agege", name: "Agege" },
      { id: "ajeromi-ifelodun", name: "Ajeromi-Ifelodun" },
      { id: "alimosho", name: "Alimosho" },
      { id: "amuwo-odofin", name: "Amuwo-Odofin" },
      { id: "apapa", name: "Apapa" },
      { id: "badagry", name: "Badagry" },
      { id: "epe", name: "Epe" },
      { id: "eti-osa", name: "Eti-Osa" },
      { id: "ibeju-lekki", name: "Ibeju-Lekki" },
      { id: "ifako-ijaiye", name: "Ifako-Ijaiye" },
      { id: "ikeja", name: "Ikeja" },
      { id: "ikorodu", name: "Ikorodu" },
      { id: "kosofe", name: "Kosofe" },
      { id: "lagos-island", name: "Lagos Island" },
      { id: "lagos-mainland", name: "Lagos Mainland" },
      { id: "mushin", name: "Mushin" },
      { id: "ojo", name: "Ojo" },
      { id: "oshodi-isolo", name: "Oshodi-Isolo" },
      { id: "shomolu", name: "Shomolu" },
      { id: "surulere", name: "Surulere" },
    ],
  },
  {
    id: "fct",
    name: "Federal Capital Territory",
    lgas: [
      { id: "abaji", name: "Abaji" },
      { id: "bwari", name: "Bwari" },
      { id: "gwagwalada", name: "Gwagwalada" },
      { id: "kuje", name: "Kuje" },
      { id: "kwali", name: "Kwali" },
      { id: "municipal-area-council", name: "Municipal Area Council" },
    ],
  },
  // Jigawa State
  {
    id: "jigawa",
    name: "Jigawa",
    lgas: [
      { id: "auyo", name: "Auyo" },
      { id: "babura", name: "Babura" },
      { id: "biriniwa", name: "Biriniwa" },
      { id: "birnin-kudu", name: "Birnin Kudu" },
      { id: "buji", name: "Buji" },
      { id: "dutse", name: "Dutse" },
      { id: "gagarawa", name: "Gagarawa" },
      { id: "garki", name: "Garki" },
      { id: "gumel", name: "Gumel" },
      { id: "guri", name: "Guri" },
      { id: "gwaram", name: "Gwaram" },
      { id: "gwiwa", name: "Gwiwa" },
      { id: "hadejia", name: "Hadejia" },
      { id: "jahun", name: "Jahun" },
      { id: "kafin-hausa", name: "Kafin Hausa" },
      { id: "kaugama", name: "Kaugama" },
      { id: "kazaure", name: "Kazaure" },
      { id: "kirikasamma", name: "Kiri Kasamma" },
      { id: "kiyawa", name: "Kiyawa" },
      { id: "maigatari", name: "Maigatari" },
      { id: "malam-madori", name: "Malam Madori" },
      { id: "ringim", name: "Ringim" },
      { id: "roni", name: "Roni" },
      { id: "sule-tankarkar", name: "Sule Tankarkar" },
      { id: "taura", name: "Taura" },
      { id: "yankwashi", name: "Yankwashi" },
    ],
  },
  // Kaduna State
  {
    id: "kaduna",
    name: "Kaduna",
    lgas: [
      { id: "birnin-gwari", name: "Birnin Gwari" },
      { id: "chikun", name: "Chikun" },
      { id: "giwa", name: "Giwa" },
      { id: "igabi", name: "Igabi" },
      { id: "ikara", name: "Ikara" },
      { id: "jaba", name: "Jaba" },
      { id: "jema'a", name: "Jema'a" },
      { id: "kachia", name: "Kachia" },
      { id: "kaduna-north", name: "Kaduna North" },
      { id: "kaduna-south", name: "Kaduna South" },
      { id: "kagarko", name: "Kagarko" },
      { id: "kajuru", name: "Kajuru" },
      { id: "kaura", name: "Kaura" },
      { id: "kauru", name: "Kauru" },
      { id: "kubau", name: "Kubau" },
      { id: "kudan", name: "Kudan" },
      { id: "lere", name: "Lere" },
      { id: "makarfi", name: "Makarfi" },
      { id: "sabon-gari", name: "Sabon Gari" },
      { id: "sanga", name: "Sanga" },
      { id: "soba", name: "Soba" },
      { id: "zangon-kataf", name: "Zangon Kataf" },
      { id: "zaria", name: "Zaria" },
    ],
  },
  // Kano State
  {
    id: "kano",
    name: "Kano",
    lgas: [
      { id: "ajingi", name: "Ajingi" },
      { id: "albasu", name: "Albasu" },
      { id: "bagwai", name: "Bagwai" },
      { id: "bebeji", name: "Bebeji" },
      { id: "bichi", name: "Bichi" },
      { id: "bunkure", name: "Bunkure" },
      { id: "dala", name: "Dala" },
      { id: "dambatta", name: "Dambatta" },
      { id: "dawakin-kudu", name: "Dawakin Kudu" },
      { id: "dawakin-tofa", name: "Dawakin Tofa" },
      { id: "doguwa", name: "Doguwa" },
      { id: "fagge", name: "Fagge" },
      { id: "gabasawa", name: "Gabasawa" },
      { id: "garko", name: "Garko" },
      { id: "garun-mallam", name: "Garun Mallam" },
      { id: "gaya", name: "Gaya" },
      { id: "gezawa", name: "Gezawa" },
      { id: "gwale", name: "Gwale" },
      { id: "gwarzo", name: "Gwarzo" },
      { id: "kabo", name: "Kabo" },
      { id: "kano-municipal", name: "Kano Municipal" },
      { id: "karaye", name: "Karaye" },
      { id: "kibiya", name: "Kibiya" },
      { id: "kiru", name: "Kiru" },
      { id: "kumbotso", name: "Kumbotso" },
      { id: "kunchi", name: "Kunchi" },
      { id: "kura", name: "Kura" },
      { id: "madobi", name: "Madobi" },
      { id: "makoda", name: "Makoda" },
      { id: "minjibir", name: "Minjibir" },
      { id: "nasarawa", name: "Nasarawa" },
      { id: "rano", name: "Rano" },
      { id: "rimin-gado", name: "Rimin Gado" },
      { id: "rogo", name: "Rogo" },
      { id: "shanono", name: "Shanono" },
      { id: "sumaila", name: "Sumaila" },
      { id: "takai", name: "Takai" },
      { id: "tarauni", name: "Tarauni" },
      { id: "tofa", name: "Tofa" },
      { id: "tsanyawa", name: "Tsanyawa" },
      { id: "tudun-wada", name: "Tudun Wada" },
      { id: "ungogo", name: "Ungogo" },
      { id: "warawa", name: "Warawa" },
      { id: "wudil", name: "Wudil" },
    ],
  },
  // Katsina State
  {
    id: "katsina",
    name: "Katsina",
    lgas: [
      { id: "bakori", name: "Bakori" },
      { id: "batagarawa", name: "Batagarawa" },
      { id: "batsari", name: "Batsari" },
      { id: "baure", name: "Baure" },
      { id: "bindawa", name: "Bindawa" },
      { id: "charanchi", name: "Charanchi" },
      { id: "dan-musa", name: "Dan Musa" },
      { id: "dandume", name: "Dandume" },
      { id: "danja", name: "Danja" },
      { id: "daura", name: "Daura" },
      { id: "dutsi", name: "Dutsi" },
      { id: "dutsin-ma", name: "Dutsin Ma" },
      { id: "faskari", name: "Faskari" },
      { id: "funtua", name: "Funtua" },
      { id: "ingawa", name: "Ingawa" },
      { id: "jibia", name: "Jibia" },
      { id: "kafur", name: "Kafur" },
      { id: "kaita", name: "Kaita" },
      { id: "kankara", name: "Kankara" },
      { id: "kankia", name: "Kankia" },
      { id: "katsina", name: "Katsina" },
      { id: "kurfi", name: "Kurfi" },
      { id: "kusada", name: "Kusada" },
      { id: "mai-adua", name: "Mai'Adua" },
      { id: "malumfashi", name: "Malumfashi" },
      { id: "mani", name: "Mani" },
      { id: "mashi", name: "Mashi" },
      { id: "matazu", name: "Matazu" },
      { id: "musawa", name: "Musawa" },
      { id: "rimi", name: "Rimi" },
      { id: "sabuwa", name: "Sabuwa" },
      { id: "safana", name: "Safana" },
      { id: "sandamu", name: "Sandamu" },
      { id: "zango", name: "Zango" },
    ],
  },
  // Kebbi State
  {
    id: "kebbi",
    name: "Kebbi",
    lgas: [
      { id: "aleiro", name: "Aleiro" },
      { id: "arewa-dandi", name: "Arewa Dandi" },
      { id: "argungu", name: "Argungu" },
      { id: "augie", name: "Augie" },
      { id: "bagudo", name: "Bagudo" },
      { id: "birnin-kebbi", name: "Birnin Kebbi" },
      { id: "bunza", name: "Bunza" },
      { id: "dandi", name: "Dandi" },
      { id: "fakai", name: "Fakai" },
      { id: "gwandu", name: "Gwandu" },
      { id: "jega", name: "Jega" },
      { id: "kalgo", name: "Kalgo" },
      { id: "koko-besse", name: "Koko/Besse" },
      { id: "maiyama", name: "Maiyama" },
      { id: "ngaski", name: "Ngaski" },
      { id: "sakaba", name: "Sakaba" },
      { id: "shanga", name: "Shanga" },
      { id: "suru", name: "Suru" },
      { id: "wasagu-danko", name: "Wasagu/Danko" },
      { id: "yauri", name: "Yauri" },
      { id: "zuru", name: "Zuru" },
    ],
  },
  // Kogi State
  {
    id: "kogi",
    name: "Kogi",
    lgas: [
      { id: "adavi", name: "Adavi" },
      { id: "ajaokuta", name: "Ajaokuta" },
      { id: "ankpa", name: "Ankpa" },
      { id: "bassa", name: "Bassa" },
      { id: "dekina", name: "Dekina" },
      { id: "ibaji", name: "Ibaji" },
      { id: "idah", name: "Idah" },
      { id: "igalamela-odolu", name: "Igalamela Odolu" },
      { id: "ijumu", name: "Ijumu" },
      { id: "kabba-bunu", name: "Kabba/Bunu" },
      { id: "kogi", name: "Kogi" },
      { id: "lokoja", name: "Lokoja" },
      { id: "mopa-muro", name: "Mopa Muro" },
      { id: "ofu", name: "Ofu" },
      { id: "ogori-magongo", name: "Ogori/Magongo" },
      { id: "okehi", name: "Okehi" },
      { id: "okene", name: "Okene" },
      { id: "olamaboro", name: "Olamaboro" },
      { id: "omala", name: "Omala" },
      { id: "yagba-east", name: "Yagba East" },
      { id: "yagba-west", name: "Yagba West" },
    ],
  },
  // Kwara State
  {
    id: "kwara",
    name: "Kwara",
    lgas: [
      { id: "asa", name: "Asa" },
      { id: "baruten", name: "Baruten" },
      { id: "edu", name: "Edu" },
      { id: "ekiti", name: "Ekiti" },
      { id: "ifelodun", name: "Ifelodun" },
      { id: "ilorin-east", name: "Ilorin East" },
      { id: "ilorin-south", name: "Ilorin South" },
      { id: "ilorin-west", name: "Ilorin West" },
      { id: "irepodun", name: "Irepodun" },
      { id: "isin", name: "Isin" },
      { id: "kaiama", name: "Kaiama" },
      { id: "moro", name: "Moro" },
      { id: "offa", name: "Offa" },
      { id: "oke-ero", name: "Oke Ero" },
      { id: "oyun", name: "Oyun" },
      { id: "pategi", name: "Pategi" },
    ],
  },
  // Nasarawa State
  {
    id: "nasarawa",
    name: "Nasarawa",
    lgas: [
      { id: "akwanga", name: "Akwanga" },
      { id: "awe", name: "Awe" },
      { id: "doma", name: "Doma" },
      { id: "karu", name: "Karu" },
      { id: "keana", name: "Keana" },
      { id: "keffi", name: "Keffi" },
      { id: "kokona", name: "Kokona" },
      { id: "lafia", name: "Lafia" },
      { id: "nasarawa", name: "Nasarawa" },
      { id: "nasarawa-eggon", name: "Nasarawa Eggon" },
      { id: "obi", name: "Obi" },
      { id: "toto", name: "Toto" },
      { id: "wamba", name: "Wamba" },
    ],
  },
  // Niger State
  {
    id: "niger",
    name: "Niger",
    lgas: [
      { id: "agaie", name: "Agaie" },
      { id: "agwara", name: "Agwara" },
      { id: "bida", name: "Bida" },
      { id: "borgu", name: "Borgu" },
      { id: "bosso", name: "Bosso" },
      { id: "chanchaga", name: "Chanchaga" },
      { id: "edati", name: "Edati" },
      { id: "gbako", name: "Gbako" },
      { id: "gurara", name: "Gurara" },
      { id: "katcha", name: "Katcha" },
      { id: "kontagora", name: "Kontagora" },
      { id: "lapai", name: "Lapai" },
      { id: "lavun", name: "Lavun" },
      { id: "magama", name: "Magama" },
      { id: "mariga", name: "Mariga" },
      { id: "mashegu", name: "Mashegu" },
      { id: "mokwa", name: "Mokwa" },
      { id: "muya", name: "Muya" },
      { id: "paikoro", name: "Paikoro" },
      { id: "rafi", name: "Rafi" },
      { id: "shiroro", name: "Shiroro" },
      { id: "suleja", name: "Suleja" },
      { id: "tafa", name: "Tafa" },
      { id: "wushishi", name: "Wushishi" },
    ],
  },
  // Ogun State
  {
    id: "ogun",
    name: "Ogun",
    lgas: [
      { id: "abeokuta-north", name: "Abeokuta North" },
      { id: "abeokuta-south", name: "Abeokuta South" },
      { id: "ado-odo-ota", name: "Ado-Odo/Ota" },
      { id: "ewekoro", name: "Ewekoro" },
      { id: "ifo", name: "Ifo" },
      { id: "ijebu-east", name: "Ijebu East" },
      { id: "ijebu-north", name: "Ijebu North" },
      { id: "ijebu-north-east", name: "Ijebu North East" },
      { id: "ijebu-ode", name: "Ijebu Ode" },
      { id: "ikenne", name: "Ikenne" },
      { id: "imeko-afon", name: "Imeko Afon" },
      { id: "ipokia", name: "Ipokia" },
      { id: "obafemi-owode", name: "Obafemi Owode" },
      { id: "odeda", name: "Odeda" },
      { id: "odogbolu", name: "Odogbolu" },
      { id: "ogun-waterside", name: "Ogun Waterside" },
      { id: "remo-north", name: "Remo North" },
      { id: "shagamu", name: "Shagamu" },
      { id: "yewa-north", name: "Yewa North" },
      { id: "yewa-south", name: "Yewa South" },
    ],
  },
  // Ondo State
  {
    id: "ondo",
    name: "Ondo",
    lgas: [
      { id: "akoko-north-east", name: "Akoko North-East" },
      { id: "akoko-north-west", name: "Akoko North-West" },
      { id: "akoko-south-east", name: "Akoko South-East" },
      { id: "akoko-south-west", name: "Akoko South-West" },
      { id: "akure-north", name: "Akure North" },
      { id: "akure-south", name: "Akure South" },
      { id: "ese-odo", name: "Ese Odo" },
      { id: "idanre", name: "Idanre" },
      { id: "ifedore", name: "Ifedore" },
      { id: "ilaje", name: "Ilaje" },
      { id: "ile-oluji-okeigbo", name: "Ile Oluji/Okeigbo" },
      { id: "irele", name: "Irele" },
      { id: "odigbo", name: "Odigbo" },
      { id: "oko-igbo", name: "Oko Igbo" },
      { id: "ondo-east", name: "Ondo East" },
      { id: "ondo-west", name: "Ondo West" },
      { id: "ose", name: "Ose" },
      { id: "owo", name: "Owo" },
    ],
  },
  // Osun State
  {
    id: "osun",
    name: "Osun",
    lgas: [
      { id: "ataoja", name: "Ataoja" },
      { id: "atakunmosa-east", name: "Atakunmosa East" },
      { id: "atakunmosa-west", name: "Atakunmosa West" },
      { id: "ayedaade", name: "Ayedaade" },
      { id: "ayedaade-east", name: "Ayedaade East" },
      { id: "ayedire", name: "Ayedire" },
      { id: "boluwaduro", name: "Boluwaduro" },
      { id: "boripe", name: "Boripe" },
      { id: "ede-north", name: "Ede North" },
      { id: "ede-south", name: "Ede South" },
      { id: "egbedore", name: "Egbedore" },
      { id: "ejigbo", name: "Ejigbo" },
      { id: "ife-central", name: "Ife Central" },
      { id: "ife-east", name: "Ife East" },
      { id: "ife-north", name: "Ife North" },
      { id: "ife-south", name: "Ife South" },
      { id: "ifelodun", name: "Ifelodun" },
      { id: "ila", name: "Ila" },
      { id: "ilesa-east", name: "Ilesa East" },
      { id: "ilesa-west", name: "Ilesa West" },
      { id: "irepodun", name: "Irepodun" },
      { id: "irewole", name: "Irewole" },
      { id: "isokan", name: "Isokan" },
      { id: "iwo", name: "Iwo" },
      { id: "obokun", name: "Obokun" },
      { id: "odo-otin", name: "Odo Otin" },
      { id: "ola-oluwa", name: "Ola Oluwa" },
      { id: "olorunda", name: "Olorunda" },
      { id: "oriade", name: "Oriade" },
      { id: "orolu", name: "Orolu" },
    ],
  },
  // Oyo State
  {
    id: "oyo",
    name: "Oyo",
    lgas: [
      { id: "afijio", name: "Afijio" },
      { id: "akinyele", name: "Akinyele" },
      { id: "atiba", name: "Atiba" },
      { id: "atifo", name: "Atifo" },
      { id: "egbeda", name: "Egbeda" },
      { id: "ibadan-north", name: "Ibadan North" },
      { id: "ibadan-north-east", name: "Ibadan North-East" },
      { id: "ibadan-north-west", name: "Ibadan North-West" },
      { id: "ibadan-south-east", name: "Ibadan South-East" },
      { id: "ibadan-south-west", name: "Ibadan South-West" },
      { id: "ibarapa-central", name: "Ibarapa Central" },
      { id: "ibarapa-east", name: "Ibarapa East" },
      { id: "ibarapa-north", name: "Ibarapa North" },
      { id: "ido", name: "Ido" },
      { id: "ifedapo", name: "Ifedapo" },
      { id: "ifeloju", name: "Ifeloju" },
      { id: "irepo", name: "Irepo" },
      { id: "iseyin", name: "Iseyin" },
      { id: "itesiwaju", name: "Itesiwaju" },
      { id: "iwajowa", name: "Iwajowa" },
      { id: "kajola", name: "Kajola" },
      { id: "lagelu", name: "Lagelu" },
      { id: "ogbomosho-north", name: "Ogbomosho North" },
      { id: "ogbomosho-south", name: "Ogbomosho South" },
      { id: "ogo-oluwa", name: "Ogo Oluwa" },
      { id: "oluyole", name: "Oluyole" },
      { id: "ona-ara", name: "Ona Ara" },
      { id: "orelope", name: "Orelope" },
      { id: "orire", name: "Orire" },
      { id: "oyo-east", name: "Oyo East" },
      { id: "oyo-west", name: "Oyo West" },
      { id: "saki-east", name: "Saki East" },
      { id: "saki-west", name: "Saki West" },
      { id: "surulere", name: "Surulere" },
    ],
  },
  // Plateau State
  {
    id: "plateau",
    name: "Plateau",
    lgas: [
      { id: "barkin-ladi", name: "Barkin Ladi" },
      { id: "bassa", name: "Bassa" },
      { id: "bokkos", name: "Bokkos" },
      { id: "jos-east", name: "Jos East" },
      { id: "jos-north", name: "Jos North" },
      { id: "jos-south", name: "Jos South" },
      { id: "kanam", name: "Kanam" },
      { id: "kanke", name: "Kanke" },
      { id: "langtang-north", name: "Langtang North" },
      { id: "langtang-south", name: "Langtang South" },
      { id: "mangu", name: "Mangu" },
      { id: "mikang", name: "Mikang" },
      { id: "pankshin", name: "Pankshin" },
      { id: "qua'an-pan", name: "Qua'an Pan" },
      { id: "riyom", name: "Riyom" },
      { id: "shendam", name: "Shendam" },
      { id: "wase", name: "Wase" },
    ],
  },
  // Rivers State
  {
    id: "rivers",
    name: "Rivers",
    lgas: [
      { id: "abua-odual", name: "Abua/Odual" },
      { id: "ahoada-east", name: "Ahoada East" },
      { id: "ahoada-west", name: "Ahoada West" },
      { id: "akuku-toru", name: "Akuku Toru" },
      { id: "andoni", name: "Andoni" },
      { id: "asari-toru", name: "Asari-Toru" },
      { id: "bonny", name: "Bonny" },
      { id: "degema", name: "Degema" },
      { id: "eleme", name: "Eleme" },
      { id: "emohua", name: "Emohua" },
      { id: "etche", name: "Etche" },
      { id: "gokana", name: "Gokana" },
      { id: "ikwerre", name: "Ikwerre" },
      { id: "khana", name: "Khana" },
      { id: "obio-akpor", name: "Obio/Akpor" },
      { id: "ogba-egbema-ndoni", name: "Ogba/Egbema/Ndoni" },
      { id: "ogu-bolo", name: "Ogu/Bolo" },
      { id: "okrika", name: "Okrika" },
      { id: "omuma", name: "Omuma" },
      { id: "opobo-nkoro", name: "Opobo/Nkoro" },
      { id: "oyigbo", name: "Oyigbo" },
      { id: "port-harcourt", name: "Port Harcourt" },
      { id: "tai", name: "Tai" },
    ],
  },
  // Sokoto State
  {
    id: "sokoto",
    name: "Sokoto",
    lgas: [
      { id: "binji", name: "Binji" },
      { id: "bodinga", name: "Bodinga" },
      { id: "dange-shuni", name: "Dange Shuni" },
      { id: "gada", name: "Gada" },
      { id: "goronyo", name: "Goronyo" },
      { id: "gudu", name: "Gudu" },
      { id: "gwadabawa", name: "Gwadabawa" },
      { id: "illela", name: "Illela" },
      { id: "isa", name: "Isa" },
      { id: "kebbe", name: "Kebbe" },
      { id: "kware", name: "Kware" },
      { id: "rabah", name: "Rabah" },
      { id: "sabon-birni", name: "Sabon Birni" },
      { id: "shagari", name: "Shagari" },
      { id: "silame", name: "Silame" },
      { id: "sokoto-north", name: "Sokoto North" },
      { id: "sokoto-south", name: "Sokoto South" },
      { id: "tambuwal", name: "Tambuwal" },
      { id: "tangaza", name: "Tangaza" },
      { id: "tureta", name: "Tureta" },
      { id: "wamakko", name: "Wamakko" },
      { id: "wurno", name: "Wurno" },
      { id: "yabo", name: "Yabo" },
    ],
  },
  // Taraba State
  {
    id: "taraba",
    name: "Taraba",
    lgas: [
      { id: "ardokola", name: "Ardo Kola" },
      { id: "bali", name: "Bali" },
      { id: "donga", name: "Donga" },
      { id: "gashaka", name: "Gashaka" },
      { id: "gassol", name: "Gassol" },
      { id: "ibi", name: "Ibi" },
      { id: "jalingo", name: "Jalingo" },
      { id: "karim-lamido", name: "Karim Lamido" },
      { id: "kurmi", name: "Kurmi" },
      { id: "lau", name: "Lau" },
      { id: "sardauna", name: "Sardauna" },
      { id: "takum", name: "Takum" },
      { id: "ussa", name: "Ussa" },
      { id: "wukari", name: "Wukari" },
      { id: "yorro", name: "Yorro" },
      { id: "zing", name: "Zing" },
    ],
  },
  // Yobe State
  {
    id: "yobe",
    name: "Yobe",
    lgas: [
      { id: "bade", name: "Bade" },
      { id: "bursari", name: "Bursari" },
      { id: "damaturu", name: "Damaturu" },
      { id: "fika", name: "Fika" },
      { id: "fune", name: "Fune" },
      { id: "geidam", name: "Geidam" },
      { id: "gulani", name: "Gulani" },
      { id: "jakusko", name: "Jakusko" },
      { id: "karasuwa", name: "Karasuwa" },
      { id: "machina", name: "Machina" },
      { id: "nagere", name: "Nagere" },
      { id: "nguru", name: "Nguru" },
      { id: "potiskum", name: "Potiskum" },
      { id: "tarmuwa", name: "Tarmuwa" },
      { id: "yunusari", name: "Yunusari" },
      { id: "yusufari", name: "Yusufari" },
    ],
  },
  // Zamfara State
  {
    id: "zamfara",
    name: "Zamfara",
    lgas: [
      { id: "anka", name: "Anka" },
      { id: "bakura", name: "Bakura" },
      { id: "birnin-magaji", name: "Birnin Magaji" },
      { id: "bukkuyum", name: "Bukkuyum" },
      { id: "bungudu", name: "Bungudu" },
      { id: "chafe", name: "Chafe" },
      { id: "gummi", name: "Gummi" },
      { id: "gusau", name: "Gusau" },
      { id: "kaura-namoda", name: "Kaura Namoda" },
      { id: "maradun", name: "Maradun" },
      { id: "maru", name: "Maru" },
      { id: "shinkafi", name: "Shinkafi" },
      { id: "talata-mafara", name: "Talata Mafara" },
      { id: "zurmi", name: "Zurmi" },
    ],
  },
  // FCT
  {
    id: "fct",
    name: "Federal Capital Territory",
    lgas: [
      { id: "abaji", name: "Abaji" },
      { id: "bwari", name: "Bwari" },
      { id: "gwagwalada", name: "Gwagwalada" },
      { id: "kuje", name: "Kuje" },
      { id: "kwali", name: "Kwali" },
      { id: "municipal-area-council", name: "Municipal Area Council" },
    ],
  },
]

/**
 * Helper function to get LGAs for a specific state
 */
export function getLGAsByState(stateId: string): LGA[] {
  const state = nigerianStates.find((state) => state.id === stateId)
  return state ? state.lgas : []
}

/**
 * Get all states as simple name-value pairs for select inputs
 */
export function getStatesAsOptions() {
  return nigerianStates.map((state) => ({
    value: state.id,
    label: state.name,
  }))
}
